// Programa:  EspNome
// Autor:     Robert Koch
// Data:      29/07/2011
// Cliente:   Nova Alianca
// Descricao: P.E. especifico para retornar o nome do modulo 'especifico', sem o qual
//            o modulo fica indisponivel para os usuarios.
//
// Historico de alteracoes:
//

// --------------------------------------------------------------------------
User Function EspNome ()
return "Cooperativa"
