// Programa...: VA_APUES
// Autor......: Cláudia Lionço
// Data.......: 16/03/2020
// Descricao..: Apuração de entradas e saídas do estoque. GLPI: 7636
//
// Historico de alteracoes:
// 17/10/2023 - Claudia - Incluida a coluna de data. GLPI: 14379
// 25/10/2023 - Claudia - Incluidas novas colunas conforme GLPI: 14386
// 27/10/2023 - Claudia - Acrescentada a unidade de medida. GLPI: 14412
// 01/11/2023 - Claudia - Acrescentado campo D1_CF. GLPI: 14431
// 09/11/2023 - Claudia - Incluido o campo de perda de op. GLPI:14457
//
// -----------------------------------------------------------------------------------------------------------
#include 'protheus.ch'
#include 'parmtype.ch'

User Function VA_APUES()
	//Local _cQry1	 := ""
	Local _oSQL      := NIL
	Private oReport
	Private cPerg   := "VA_APUES"
	
	_ValidPerg()
	Pergunte(cPerg,.T.)
	
	_AnoRef 	:= mv_par01
	_MesRef 	:= PADL(mv_par02,2,'0')
	_DtRefIni   := STOD(_AnoRef + _MesRef + '01')
	_DtRefFin	:= LastDate(_DtRefIni)
	
	_DtAntIni   := MonthSub(_DtRefIni,1)
	_DtAntFin	:= LastDate(_DtAntIni)
	
	_oSQL := ClsSQL():New ()

	_oSQL:_sQuery += " 	WITH entSaida "
	_oSQL:_sQuery += " 	AS "
	_oSQL:_sQuery += " 	( "
	//	--Saldo Inicial - OK
	_oSQL:_sQuery += " SELECT "
	_oSQL:_sQuery += " 			SUM(B9_VINI1) AS VALOR "
	_oSQL:_sQuery += " 		   ,B9_DATA AS DATA "
	_oSQL:_sQuery += " 		   ,B9_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,B9_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'01-Saldo_Inicial' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,'SI' AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,B9_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,SUM(B9_QINI) AS QTD "
	_oSQL:_sQuery += " 		   ,'' AS OP "
	_oSQL:_sQuery += " 		   ,'' AS CF "
	_oSQL:_sQuery += "         ,'' AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SB9010 "
	_oSQL:_sQuery += " 		WHERE B9_DATA BETWEEN '" + dtos(_DtAntIni) + "' AND '" + dtos(_DtAntFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		GROUP BY B9_COD "
	_oSQL:_sQuery += " 				,B9_FILIAL "
	_oSQL:_sQuery += " 				,B9_LOCAL "
	_oSQL:_sQuery += " 				,B9_DATA "

	_oSQL:_sQuery += " 		UNION  "
	//	--Saldo final - OK	
	_oSQL:_sQuery += " 		SELECT "
	_oSQL:_sQuery += " 			-SUM(B9_VINI1) AS VALOR "
	_oSQL:_sQuery += " 		   ,B9_DATA AS DATA "
	_oSQL:_sQuery += " 		   ,B9_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,B9_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'13-Saldo_Final' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,'SF' AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,B9_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,-SUM(B9_QINI) AS QTD "
	_oSQL:_sQuery += " 		   ,'' AS OP "
	_oSQL:_sQuery += " 		   ,'' AS CF "
	_oSQL:_sQuery += "         ,'' AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SB9010 "
	_oSQL:_sQuery += " 		WHERE B9_DATA BETWEEN '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		GROUP BY B9_COD "
	_oSQL:_sQuery += " 				,B9_FILIAL "
	_oSQL:_sQuery += " 				,B9_LOCAL "
	_oSQL:_sQuery += " 				,B9_DATA "

	_oSQL:_sQuery += " 		UNION  "
	//	--compras - OK - Está somando as entradas de transferencias
	_oSQL:_sQuery += " 	SELECT
	_oSQL:_sQuery += " 			SUM(D1_CUSTO) AS VALOR "
	_oSQL:_sQuery += " 		   ,D1_DTDIGIT AS DATA "
	_oSQL:_sQuery += " 		   ,D1_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,D1_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'02-Compras' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,D1_DOC AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,D1_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,SUM(D1_QUANT) AS QTD "
	_oSQL:_sQuery += " 		   ,'' AS OP "
	_oSQL:_sQuery += " 		   ,'' AS CF "
	_oSQL:_sQuery += "         ,'' AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SD1010 "
	_oSQL:_sQuery += " 		WHERE D1_DTDIGIT BETWEEN  '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND D1_TES IN (SELECT "
	_oSQL:_sQuery += " 				F4_CODIGO "
	_oSQL:_sQuery += " 			FROM SF4010 "
	_oSQL:_sQuery += " 			WHERE F4_ESTOQUE = 'S' "
	_oSQL:_sQuery += " 			AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 			AND F4_PODER3 = 'N' "
	_oSQL:_sQuery += " 			AND F4_TRANFIL != '1' "
	_oSQL:_sQuery += " 			AND F4_TIPO = 'E') "
	_oSQL:_sQuery += " 		GROUP BY D1_COD "
	_oSQL:_sQuery += " 				,D1_FILIAL "
	_oSQL:_sQuery += " 				,D1_DOC "
	_oSQL:_sQuery += " 				,D1_LOCAL "
	_oSQL:_sQuery += " 				,D1_DTDIGIT "

	_oSQL:_sQuery += " 		UNION  "
	//	--Vendas - OK - ver tranfil pois deve estar contabilizando as transferencias como se fossem compra	
	_oSQL:_sQuery += " 		SELECT "
	_oSQL:_sQuery += " 			-SUM(D2_CUSTO1) AS VALOR "
	_oSQL:_sQuery += " 		   ,D2_EMISSAO AS DATA "
	_oSQL:_sQuery += " 		   ,D2_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,D2_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'12-Saida_Vendas' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,D2_DOC AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,D2_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,-SUM(D2_QUANT) AS QTD "
	_oSQL:_sQuery += " 		   ,'' AS OP "
	_oSQL:_sQuery += " 		   ,'' AS CF "
	_oSQL:_sQuery += "         ,'' AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SD2010 "
	_oSQL:_sQuery += " 		WHERE D2_COD IN (SELECT "
	_oSQL:_sQuery += " 				B1_COD "
	_oSQL:_sQuery += " 			FROM SB1010 "
	_oSQL:_sQuery += " 			WHERE D_E_L_E_T_ = '') "
	_oSQL:_sQuery += " 		AND D2_EMISSAO BETWEEN  '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND D2_TES IN (SELECT "
	_oSQL:_sQuery += " 				F4_CODIGO "
	_oSQL:_sQuery += " 			FROM SF4010 "
	_oSQL:_sQuery += " 			WHERE F4_ESTOQUE = 'S' "
	_oSQL:_sQuery += " 			AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 			AND F4_PODER3 = 'N' "
	_oSQL:_sQuery += " 			AND F4_TRANFIL != '1' "
	_oSQL:_sQuery += " 			AND F4_TIPO = 'S') "
	_oSQL:_sQuery += " 		GROUP BY D2_COD "
	_oSQL:_sQuery += " 				,D2_FILIAL "
	_oSQL:_sQuery += " 				,D2_DOC "
	_oSQL:_sQuery += " 				,D2_LOCAL "
	_oSQL:_sQuery += " 				,D2_EMISSAO "

	_oSQL:_sQuery += " 		UNION  "
		
	_oSQL:_sQuery += " 		SELECT "
	_oSQL:_sQuery += " 			SUM(D1_CUSTO) AS VALOR "
	_oSQL:_sQuery += " 		   ,D1_DTDIGIT AS DATA "
	_oSQL:_sQuery += " 		   ,D1_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,D1_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'05-Entrada_transf' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,D1_DOC AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,D1_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,SUM(D1_QUANT) AS QTD "
	_oSQL:_sQuery += " 		   ,'' AS OP "
	_oSQL:_sQuery += " 		   ,'' AS CF "
	_oSQL:_sQuery += "         ,'' AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SD1010 "
	_oSQL:_sQuery += " 		WHERE D1_COD IN (SELECT "
	_oSQL:_sQuery += " 				B1_COD "
	_oSQL:_sQuery += " 			FROM SB1010 "
	_oSQL:_sQuery += " 			WHERE D_E_L_E_T_ = '') "
	_oSQL:_sQuery += " 		AND D1_DTDIGIT BETWEEN '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND D1_TES IN (SELECT "
	_oSQL:_sQuery += " 				F4_CODIGO "
	_oSQL:_sQuery += " 			FROM SF4010 "
	_oSQL:_sQuery += " 			WHERE F4_ESTOQUE = 'S' "
	_oSQL:_sQuery += " 			AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 			AND F4_TRANFIL = '1') "
	_oSQL:_sQuery += " 		GROUP BY D1_COD "
	_oSQL:_sQuery += " 				,D1_FILIAL "
	_oSQL:_sQuery += " 				,D1_DOC "
	_oSQL:_sQuery += " 				,D1_LOCAL "
	_oSQL:_sQuery += " 				,D1_DTDIGIT "

	_oSQL:_sQuery += " 		UNION  "
	//	--Saídas TRANSFERENCIAS	
	_oSQL:_sQuery += " 		SELECT "
	_oSQL:_sQuery += " 			-SUM(D2_CUSTO1) AS VALOR "
	_oSQL:_sQuery += " 		   ,D2_EMISSAO AS DATA "
	_oSQL:_sQuery += " 		   ,D2_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,D2_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'06-Saida_transf' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,D2_DOC AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,D2_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,-SUM(D2_QUANT) AS QTD "
	_oSQL:_sQuery += " 		   ,'' AS OP "
	_oSQL:_sQuery += " 		   ,'' AS CF "
	_oSQL:_sQuery += "         ,'' AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SD2010 "
	_oSQL:_sQuery += " 		WHERE D2_EMISSAO BETWEEN '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND D2_TES IN (SELECT "
	_oSQL:_sQuery += " 				F4_CODIGO "
	_oSQL:_sQuery += " 			FROM SF4010 "
	_oSQL:_sQuery += " 			WHERE F4_ESTOQUE = 'S' "
	_oSQL:_sQuery += " 			AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 			AND F4_CONTERC != 'S' "
	_oSQL:_sQuery += " 			AND F4_TRANFIL = '1') "
	_oSQL:_sQuery += " 		GROUP BY D2_COD "
	_oSQL:_sQuery += " 				,D2_FILIAL "
	_oSQL:_sQuery += " 				,D2_DOC "
	_oSQL:_sQuery += " 				,D2_LOCAL "
	_oSQL:_sQuery += " 				,D2_EMISSAO "

	_oSQL:_sQuery += " 		UNION  "
	//	--compras Terceiros - OK	
	_oSQL:_sQuery += " 		SELECT "
	_oSQL:_sQuery += " 			SUM(D1_CUSTO) AS VALOR "
	_oSQL:_sQuery += " 		   ,D1_DTDIGIT AS DATA "
	_oSQL:_sQuery += " 		   ,D1_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,D1_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'07-Entradas_Terceiros' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,D1_DOC AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,D1_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,SUM(D1_QUANT) AS QTD "
	_oSQL:_sQuery += " 		   ,'' AS OP "
	_oSQL:_sQuery += " 		   ,'' AS CF "
	_oSQL:_sQuery += "         ,'' AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SD1010 "
	_oSQL:_sQuery += " 		WHERE D1_DTDIGIT BETWEEN '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND D1_TES IN (SELECT "
	_oSQL:_sQuery += " 				F4_CODIGO "
	_oSQL:_sQuery += " 			FROM SF4010 "
	_oSQL:_sQuery += " 			WHERE F4_ESTOQUE = 'S' "
	_oSQL:_sQuery += " 			AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 			AND F4_PODER3 != 'N' "
	_oSQL:_sQuery += " 			AND F4_TRANFIL != '1') "
	_oSQL:_sQuery += " 		GROUP BY D1_COD "
	_oSQL:_sQuery += " 				,D1_FILIAL "
	_oSQL:_sQuery += " 				,D1_DOC "
	_oSQL:_sQuery += " 				,D1_LOCAL "
	_oSQL:_sQuery += " 				,D1_DTDIGIT "

	_oSQL:_sQuery += " 		UNION  "
	//	--Saídas Terceiros - OK	
	_oSQL:_sQuery += " 		SELECT "
	_oSQL:_sQuery += " 			-SUM(D2_CUSTO1) AS VALOR "
	_oSQL:_sQuery += " 		   ,D2_EMISSAO AS DATA "
	_oSQL:_sQuery += " 		   ,D2_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,D2_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'08-Saidas_Terceiros' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,D2_DOC AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,D2_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,-SUM(D2_QUANT) AS QTD "
	_oSQL:_sQuery += " 		   ,'' AS OP "
	_oSQL:_sQuery += " 		   ,'' AS CF "
	_oSQL:_sQuery += "         ,'' AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SD2010 "
	_oSQL:_sQuery += " 		WHERE D2_EMISSAO BETWEEN '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND D2_TES IN (SELECT "
	_oSQL:_sQuery += " 				F4_CODIGO "
	_oSQL:_sQuery += " 			FROM SF4010 "
	_oSQL:_sQuery += " 			WHERE F4_ESTOQUE = 'S' "
	_oSQL:_sQuery += " 			AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 			AND F4_PODER3 != 'N' "
	_oSQL:_sQuery += " 			AND F4_TRANFIL != '1') "
	_oSQL:_sQuery += " 		GROUP BY D2_COD "
	_oSQL:_sQuery += " 				,D2_FILIAL "
	_oSQL:_sQuery += " 				,D2_DOC "
	_oSQL:_sQuery += " 				,D2_LOCAL "
	_oSQL:_sQuery += " 				,D2_EMISSAO "

	_oSQL:_sQuery += " 		UNION  "
	//	-- MOVIMENTOações internas	
	_oSQL:_sQuery += " 		SELECT "
	_oSQL:_sQuery += " 			SUM(CASE "
	_oSQL:_sQuery += " 				WHEN D3_CF LIKE 'RE%' THEN -D3_CUSTO1 "
	_oSQL:_sQuery += " 				ELSE D3_CUSTO1 "
	_oSQL:_sQuery += " 			END) AS VALOR "
	_oSQL:_sQuery += " 		   ,D3_EMISSAO AS DATA "
	_oSQL:_sQuery += " 		   ,D3_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,D3_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'09-Movimento_Interno' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,D3_DOC AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,D3_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,SUM(CASE "
	_oSQL:_sQuery += " 				WHEN D3_CF LIKE 'RE%' THEN -D3_QUANT "
	_oSQL:_sQuery += " 				ELSE D3_QUANT "
	_oSQL:_sQuery += " 			END) AS QTD "
	_oSQL:_sQuery += " 		   ,D3_OP AS OP "
	_oSQL:_sQuery += " 		   ,D3_CF AS CF "
	_oSQL:_sQuery += "         ,D3_VAPEROP AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SD3010 "
	_oSQL:_sQuery += " 		WHERE D3_OP = '' "
	_oSQL:_sQuery += " 		AND D3_EMISSAO BETWEEN '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND D3_ESTORNO = '' "
	_oSQL:_sQuery += " 		AND D3_CF != 'PR0' "
	_oSQL:_sQuery += " 		AND D3_CF NOT LIKE '%4' "
	_oSQL:_sQuery += " 		GROUP BY D3_COD "
	_oSQL:_sQuery += " 				,D3_FILIAL "
	_oSQL:_sQuery += " 				,D3_DOC "
	_oSQL:_sQuery += " 				,D3_LOCAL "
	_oSQL:_sQuery += " 				,D3_EMISSAO "
	_oSQL:_sQuery += " 				,D3_OP "
	_oSQL:_sQuery += " 				,D3_CF "
	_oSQL:_sQuery += "         		,D3_VAPEROP  "

	_oSQL:_sQuery += " 		UNION "
	//	-- REQUISIÇÃO PARA OP - erro
	_oSQL:_sQuery += " 		SELECT "
	_oSQL:_sQuery += " 			SUM(CASE "
	_oSQL:_sQuery += " 				WHEN D3_CF LIKE 'RE%' THEN -D3_CUSTO1 "
	_oSQL:_sQuery += " 				ELSE D3_CUSTO1 "
	_oSQL:_sQuery += " 			END) AS VALOR "
	_oSQL:_sQuery += " 		   ,D3_EMISSAO AS DATA "
	_oSQL:_sQuery += " 		   ,D3_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,D3_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'10-Requisicao_OP' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,D3_DOC AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,D3_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,SUM(CASE "
	_oSQL:_sQuery += " 				WHEN D3_CF LIKE 'RE%' THEN -D3_QUANT "
	_oSQL:_sQuery += " 				ELSE D3_QUANT "
	_oSQL:_sQuery += " 			END) AS QTD "
	_oSQL:_sQuery += " 		   ,D3_OP AS OP "
	_oSQL:_sQuery += " 		   ,D3_CF AS CF "
	_oSQL:_sQuery += "         ,D3_VAPEROP AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SD3010 "
	_oSQL:_sQuery += " 		WHERE D3_OP != '' "
	_oSQL:_sQuery += " 		AND D3_EMISSAO BETWEEN  '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND D3_ESTORNO = '' "
	_oSQL:_sQuery += " 		AND D3_CF != 'PR0' "
	_oSQL:_sQuery += " 		AND D3_CF NOT LIKE '%4' "
	_oSQL:_sQuery += " 		GROUP BY D3_COD "
	_oSQL:_sQuery += " 				,D3_FILIAL "
	_oSQL:_sQuery += " 				,D3_DOC "
	_oSQL:_sQuery += " 				,D3_LOCAL "
	_oSQL:_sQuery += " 				,D3_EMISSAO "
	_oSQL:_sQuery += " 				,D3_OP "
	_oSQL:_sQuery += " 				,D3_CF "
	_oSQL:_sQuery += "         		,D3_VAPEROP "

	_oSQL:_sQuery += " 		UNION "
	//	-- Produção Por OP - OK	
	_oSQL:_sQuery += " 		SELECT "
	_oSQL:_sQuery += " 			SUM(CASE "
	_oSQL:_sQuery += " 				WHEN D3_CF LIKE 'RE%' THEN -D3_CUSTO1 "
	_oSQL:_sQuery += " 				ELSE D3_CUSTO1 "
	_oSQL:_sQuery += " 			END) AS VALOR "
	_oSQL:_sQuery += " 		   ,D3_EMISSAO AS DATA "
	_oSQL:_sQuery += " 		   ,D3_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,D3_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'11-Produção_OP' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,D3_DOC AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,D3_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,SUM(CASE "
	_oSQL:_sQuery += " 				WHEN D3_CF LIKE 'RE%' THEN -D3_QUANT "
	_oSQL:_sQuery += " 				ELSE D3_QUANT "
	_oSQL:_sQuery += " 			END) AS QTD "
	_oSQL:_sQuery += " 		   ,D3_OP AS OP "
	_oSQL:_sQuery += " 		   ,D3_CF AS CF "
	_oSQL:_sQuery += "         ,D3_VAPEROP AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SD3010 "
	_oSQL:_sQuery += " 		WHERE D3_OP != '' "
	_oSQL:_sQuery += " 		AND D3_EMISSAO BETWEEN  '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND D3_ESTORNO = '' "
	_oSQL:_sQuery += " 		AND D3_CF = 'PR0' "
	_oSQL:_sQuery += " 		AND D3_CF NOT LIKE '%4' "
	_oSQL:_sQuery += " 		GROUP BY D3_COD "
	_oSQL:_sQuery += " 				,D3_FILIAL "
	_oSQL:_sQuery += " 				,D3_DOC "
	_oSQL:_sQuery += " 				,D3_LOCAL "
	_oSQL:_sQuery += " 				,D3_EMISSAO "
	_oSQL:_sQuery += " 				,D3_OP "
	_oSQL:_sQuery += " 				,D3_CF "
	_oSQL:_sQuery += "         		,D3_VAPEROP "

	_oSQL:_sQuery += " 		UNION "
	//	--transferencias internas
	_oSQL:_sQuery += " 		SELECT "
	_oSQL:_sQuery += " 			SUM(CASE "
	_oSQL:_sQuery += " 				WHEN D3_CF LIKE 'RE%' THEN -D3_CUSTO1 "
	_oSQL:_sQuery += " 				ELSE D3_CUSTO1 "
	_oSQL:_sQuery += " 			END) AS VALOR "
	_oSQL:_sQuery += " 		   ,D3_EMISSAO AS DATA "
	_oSQL:_sQuery += " 		   ,D3_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,D3_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'04-Saida_Transf_Interna' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,D3_DOC AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,D3_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,SUM(CASE "
	_oSQL:_sQuery += " 				WHEN D3_CF LIKE 'RE%' THEN -D3_QUANT "
	_oSQL:_sQuery += " 				ELSE D3_QUANT "
	_oSQL:_sQuery += " 			END) AS QTD "
	_oSQL:_sQuery += " 		   ,D3_OP AS OP "
	_oSQL:_sQuery += " 		   ,D3_CF AS CF "
	_oSQL:_sQuery += "         ,D3_VAPEROP AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SD3010 "
	_oSQL:_sQuery += " 		WHERE D3_OP = '' "
	_oSQL:_sQuery += " 		AND D3_EMISSAO BETWEEN  '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND D3_ESTORNO = '' "
	_oSQL:_sQuery += " 		AND D3_CF != 'PR0' "
	_oSQL:_sQuery += " 		AND D3_CF LIKE 'RE4' "
	_oSQL:_sQuery += " 		GROUP BY D3_COD "
	_oSQL:_sQuery += " 				,D3_FILIAL "
	_oSQL:_sQuery += " 				,D3_DOC "
	_oSQL:_sQuery += " 				,D3_LOCAL "
	_oSQL:_sQuery += " 				,D3_EMISSAO "
	_oSQL:_sQuery += " 				,D3_OP "
	_oSQL:_sQuery += " 				,D3_CF "
	_oSQL:_sQuery += "         		,D3_VAPEROP "

	_oSQL:_sQuery += " 		UNION  "
	//	--transferencia interna	
	_oSQL:_sQuery += " 		SELECT "
	_oSQL:_sQuery += " 			SUM(CASE "
	_oSQL:_sQuery += " 				WHEN D3_CF LIKE 'RE%' THEN -D3_CUSTO1 "
	_oSQL:_sQuery += " 				ELSE D3_CUSTO1 "
	_oSQL:_sQuery += " 			END) AS VALOR "
	_oSQL:_sQuery += " 		   ,D3_EMISSAO AS DATA "
	_oSQL:_sQuery += " 		   ,D3_COD AS CODIGO "
	_oSQL:_sQuery += " 		   ,D3_FILIAL AS FILIAL "
	_oSQL:_sQuery += " 		   ,'03-Entrada_Transf_Interna' AS MOVIMENTO "
	_oSQL:_sQuery += " 		   ,D3_DOC AS DOCUMENTO "
	_oSQL:_sQuery += " 		   ,D3_LOCAL AS AX "
	_oSQL:_sQuery += " 		   ,SUM(CASE "
	_oSQL:_sQuery += " 				WHEN D3_CF LIKE 'RE%' THEN -D3_QUANT "
	_oSQL:_sQuery += " 				ELSE D3_QUANT "
	_oSQL:_sQuery += " 			END) AS QTD "
	_oSQL:_sQuery += " 		   ,D3_OP AS OP "
	_oSQL:_sQuery += " 		   ,D3_CF AS CF "
	_oSQL:_sQuery += "         ,D3_VAPEROP AS PERDA_OP "
	_oSQL:_sQuery += " 		FROM SD3010 "
	_oSQL:_sQuery += " 		WHERE D3_OP = '' "
	_oSQL:_sQuery += " 		AND D3_EMISSAO BETWEEN  '" + dtos(_DtRefIni) + "' AND '" + dtos(_DtRefFin) + "'"
	_oSQL:_sQuery += " 		AND D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND D3_ESTORNO = '' "
	_oSQL:_sQuery += " 		AND D3_CF != 'PR0' "
	_oSQL:_sQuery += " 		AND D3_CF LIKE 'DE4' "
	_oSQL:_sQuery += " 		GROUP BY D3_COD "
	_oSQL:_sQuery += " 				,D3_FILIAL "
	_oSQL:_sQuery += " 				,D3_DOC "
	_oSQL:_sQuery += " 				,D3_EMISSAO "
	_oSQL:_sQuery += " 				,D3_LOCAL "
	_oSQL:_sQuery += " 				,D3_OP "
	_oSQL:_sQuery += " 				,D3_CF "
	_oSQL:_sQuery += "         		,D3_VAPEROP "
	_oSQL:_sQuery += "               ) "

	_oSQL:_sQuery += " 	SELECT "
	_oSQL:_sQuery += " 		B1_TIPO AS TIPO "
	_oSQL:_sQuery += " 	   ,SX5.X5_DESCRI AS DESC_TIPO "
	_oSQL:_sQuery += " 	   ,SUBSTRING(DATA, 7, 2) + '/' + SUBSTRING(DATA, 5, 2) + '/' + SUBSTRING(DATA, 1, 4) AS DATA "
	_oSQL:_sQuery += " 	   ,CODIGO "
	_oSQL:_sQuery += " 	   ,SB1.B1_DESC AS DESC_PRODUTO "
	_oSQL:_sQuery += " 	   ,SB1.B1_UM AS UNIDADE_MEDIDA "
	_oSQL:_sQuery += " 	   ,SUM(VALOR) AS VALOR "
	_oSQL:_sQuery += " 	   ,DOCUMENTO "
	_oSQL:_sQuery += "     ,MOVIMENTO "
	_oSQL:_sQuery += "     ,FILIAL "
	_oSQL:_sQuery += "     ,AX "
	_oSQL:_sQuery += "     ,SUM(QTD) AS QTD "
	_oSQL:_sQuery += "     ,CASE WHEN SUM(QTD) <> 0 THEN SUM(VALOR)/SUM(QTD) ELSE 0 END AS CUSTO_UNIT "
	_oSQL:_sQuery += "     ,OP "
	_oSQL:_sQuery += "     ,CF "
	_oSQL:_sQuery += "     ,CASE "
	_oSQL:_sQuery += "  		WHEN CF = 'RE0' THEN 'Requisicao manual' "
	_oSQL:_sQuery += "  		WHEN CF = 'RE1' THEN 'Requisicao automatica' "
	_oSQL:_sQuery += "  		WHEN CF = 'RE2' THEN 'Requisicao automatica de material de apropriacao indireta' "
	_oSQL:_sQuery += "  		WHEN CF = 'RE3' THEN 'transferencia em geral' "
	_oSQL:_sQuery += "  		WHEN CF = 'RE4' THEN 'Requisicao por transferencia' "
	_oSQL:_sQuery += "  		WHEN CF = 'RE5' THEN 'Requisicao informando OP na nota fiscal de entrada' "
	_oSQL:_sQuery += "  		WHEN CF = 'RE6' THEN 'Requisicao valorizada'
	_oSQL:_sQuery += "  		WHEN CF = 'RE7' THEN 'Requisicao para transferencia de um para “N”' "
	_oSQL:_sQuery += "  		WHEN CF = 'RE9' THEN 'Requisicao para OP sem agregar custo' "
	_oSQL:_sQuery += "  		WHEN CF = 'DE0' THEN 'Devolucao manual' "
	_oSQL:_sQuery += "  		WHEN CF = 'DE1' THEN 'Devolucao automatica - estorno da Producao' "
	_oSQL:_sQuery += "  		WHEN CF = 'DE2' THEN 'Devolucao automatica de material de apropriacao indireta - estorno da Producao.' "
	_oSQL:_sQuery += "  		WHEN CF = 'DE3' THEN 'Estorno de transferencia para local de apropriacao indireta.' "
	_oSQL:_sQuery += "  		WHEN CF = 'DE4' THEN 'Devolucao de transferencia entre locais.' "
	_oSQL:_sQuery += "  		WHEN CF = 'DE5' THEN 'Devolucao de material apropriado em OP - (exclusão de nota fiscal de entrada)' "
	_oSQL:_sQuery += "  		WHEN CF = 'DE6' THEN 'Devolucao valorizada' "
	_oSQL:_sQuery += "  		WHEN CF = 'DE7' THEN 'Devolucao de transferencia de um para “N”' "
	_oSQL:_sQuery += "  		WHEN CF = 'DE9' THEN 'Devolucao para OP sem agregar custo.' "
	_oSQL:_sQuery += "  		WHEN CF = 'PR0' THEN 'Producao manual' "
	_oSQL:_sQuery += "  		WHEN CF = 'PR1' THEN 'Producao automatica' "
	_oSQL:_sQuery += "  		WHEN CF = 'ER0' THEN 'Estorno de Producao manual' "
	_oSQL:_sQuery += "  		WHEN CF = 'ER1' THEN 'Estorno de Producao automatica' "
	_oSQL:_sQuery += "  	END "
	_oSQL:_sQuery += "      ,PERDA_OP "
	_oSQL:_sQuery += " FROM entSaida "
	_oSQL:_sQuery += " LEFT JOIN SB1010 SB1 "
	_oSQL:_sQuery += " 	ON SB1.D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND entSaida.CODIGO = B1_COD "
	_oSQL:_sQuery += " LEFT JOIN SX5010 SX5 "
	_oSQL:_sQuery += " 	ON SX5.D_E_L_E_T_ = '' "
	_oSQL:_sQuery += " 		AND X5_TABELA = '02' "
	_oSQL:_sQuery += " 		AND SX5.X5_CHAVE = SB1.B1_TIPO "
	_oSQL:_sQuery += " GROUP BY B1_TIPO "
	_oSQL:_sQuery += " 		,SX5.X5_DESCRI "
	_oSQL:_sQuery += " 		,DATA "
	_oSQL:_sQuery += " 		,MOVIMENTO "
	_oSQL:_sQuery += " 		,DOCUMENTO "
	_oSQL:_sQuery += " 		,FILIAL "
	_oSQL:_sQuery += " 		,CODIGO "
	_oSQL:_sQuery += " 		,SB1.B1_DESC "
	_oSQL:_sQuery += " 		,SB1.B1_UM "
	_oSQL:_sQuery += " 		,AX "
	_oSQL:_sQuery += " 		,OP "
	_oSQL:_sQuery += " 		,CF "
	_oSQL:_sQuery += " 		,PERDA_OP "
	_oSQL:Log ()
	
	_oSQL:Qry2Xls ()	
Return
//
// --------------------------------------------------------------------------------
// Perguntas
Static Function _ValidPerg ()
    local _aRegsPerg := {}
    //                     PERGUNT                TIPO TAM DEC VALID F3     Opcoes                      				Help
    aadd (_aRegsPerg, {01, "Ano de referência      	", "C", 4, 0,  "",  "   ", {},                         					""})
    aadd (_aRegsPerg, {02, "Mês de referência   	", "C", 2, 0,  "",  "   ", {},                         					""})
    
     U_ValPerg (cPerg, _aRegsPerg)
Return
