//  Programa...: VA_COMRDEV
//  Autor......: Cláudia Lionço
//  Data.......: 15/10/2020
//  Cliente....: Alianca
//  Descricao..: Relatório de devoluções para Comissoes
//
// #TipoDePrograma    #relatorio
// #PalavasChave      #comissoes #devolucao #representante 
// #TabelasPrincipais #SE5 #SA1
// #Modulos 		  #FIN 
//
// Historico de alteracoes:
//
// --------------------------------------------------------------------------
#include 'protheus.ch'
#include 'parmtype.ch'
