//  Programa...: VA_COMVERB
//  Autor......: Cláudia Lionço
//  Cliente....: Alianca
//  Descricao..: Consulta com retorno de dados de verbas para comissões
//
// #TipoDePrograma    #consulta
// #PalavasChave      #comissoes #verbas #bonificação #comissões #representante #comissão 
// #TabelasPrincipais #SE3 #SE1 #SF2 #SD2 #SE5 #SA3
// #Modulos 		  #FIN 
//
// TIPOS DE VERBAS
// 1 - VERBAS DO MES'
// 2 - VERBA DE OUTROS NO TITULO
// 3 - BONIFICAÇÕES' 
// 4 - VERBAS BOLETO/DEP' 
// 5 - VERBA EM TITULO DE OUTROS
// 6 - VERBA EM TITULO SEM COMISSAO
//
//  Historico de alteracoes:
//
// --------------------------------------------------------------------------

#include 'protheus.ch'
#include 'parmtype.ch'

User Function VA_COMVERB(_dtaIni, _dtaFin, _sVend, _nLibPg)
	Local _oSQL    := ClsSQL ():New ()
	Local _aRet    := {}
	
	_dtaAnt := DaySub(_dtaFin,180) // diminui 6 meses
	
	//-- VERBA DO VENDEDOR NO MES
	_oSQL:_sQuery := ""
	_oSQL:_sQuery += " SELECT"
	_oSQL:_sQuery += " 	  '1 - VERBAS DO MES' AS TIPO"
	_oSQL:_sQuery += "    ,ZA4_VEND AS VENDEDOR_VERBA"
	_oSQL:_sQuery += "    ,E3_VEND AS VENDEDOR_NOTA"
	_oSQL:_sQuery += "    ,ZA5_NUM AS VERBA"
	_oSQL:_sQuery += "    ,E3_NUM AS NOTA"
	_oSQL:_sQuery += "    ,E3_PREFIXO AS SERIE"
	_oSQL:_sQuery += "    ,E3_CODCLI AS CLIENTE"
	_oSQL:_sQuery += "    ,E3_LOJA AS LOJA"
	_oSQL:_sQuery += "    ,E3_PORC AS PERCENTUAL"
	_oSQL:_sQuery += "    ,ZA5.ZA5_VLR AS BASE_COMISSAO"
	_oSQL:_sQuery += "    ,(ZA5.ZA5_VLR * E3_PORC/ 100)* -1  AS COMISSAO"
	_oSQL:_sQuery += "    ,'DESCONTO' AS TP"
    _oSQL:_sQuery += " 	  ,'1' AS TPO"
    _oSQL:_sQuery += "    ,ZA5.ZA5_FILIAL AS FILIAL"
    _oSQL:_sQuery += "    ,ZA5.ZA5_SEQ AS SEQUENCIA"
    _oSQL:_sQuery += "    ,ZA5.ZA5_DTA AS DTA"
    _oSQL:_sQuery += "    ,SE3.E3_DATA AS DTPGTOCOM"
	_oSQL:_sQuery += " FROM " + RetSQLName ("ZA5") + " ZA5 "
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("ZA4") + " ZA4 "
	_oSQL:_sQuery += " 	ON (ZA4.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND ZA4_FILIAL = '" + xFilial('ZA4') + "' " 
	_oSQL:_sQuery += " 			AND ZA4_NUM = ZA5_NUM"
	_oSQL:_sQuery += " 			AND ZA4_VEND != ''"
	_oSQL:_sQuery += " 			AND ZA4_VEND = '"+ alltrim(_sVend) +"')"
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("SA3") + " SA3 "
	_oSQL:_sQuery += " 	ON (SA3.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND SA3.A3_COD = ZA4.ZA4_VEND)"
	_oSQL:_sQuery += " LEFT JOIN " + RetSQLName ("SE3") + " SE3 "
	_oSQL:_sQuery += " 	ON (SE3.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND E3_BAIEMI = 'B'"
	_oSQL:_sQuery += " 			AND E3_VEND = '"+ alltrim(_sVend) +"'"
	Do case
		Case _nLibPg = 1	
			_oSQL:_sQuery += " 			AND E3_DATA = ''" // comissoes liberadas
		Case _nLibPg = 2
			_oSQL:_sQuery += " 			AND E3_DATA != ''" // comissoes pagas
		Case _nLibPg = 3
			// na rotina automatica não irá verificar a data, gravando a data do E3 ou vazio no ZB0_DTPGTO
	EndCase
	_oSQL:_sQuery += " 			AND E3_NUM = ZA5_DOC"
	_oSQL:_sQuery += " 			AND E3_PREFIXO = ZA5_PREFIX"
	_oSQL:_sQuery += " 			AND E3_PARCELA = ZA5_PARC"
	_oSQL:_sQuery += " 			AND E3_CODCLI = ZA5_CLI"
	_oSQL:_sQuery += " 			AND E3_LOJA = ZA5_LOJA"
	_oSQL:_sQuery += " 			AND E3_EMISSAO < '" + dtos(_dtaIni)+"'"
	_oSQL:_sQuery += " 		)"
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("SE1") + " SE1 "
	_oSQL:_sQuery += " 	ON (SE1.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND SE1.E1_FILIAL = E3_FILIAL"
	_oSQL:_sQuery += " 			AND SE1.E1_NUM = E3_NUM"
	_oSQL:_sQuery += " 			AND SE1.E1_PREFIXO = E3_PREFIXO"
	_oSQL:_sQuery += " 			AND SE1.E1_PARCELA = E3_PARCELA)"
	_oSQL:_sQuery += " WHERE ZA5.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " AND ZA5_FILIAL = '" + xFilial('ZA5') + "' " 
	_oSQL:_sQuery += " AND ZA5_DTA BETWEEN '" + dtos(_dtaIni) + "' AND '" + dtos(_dtaFin) + "'"
	
	_oSQL:_sQuery += " UNION ALL"
	
	//-- VERBAS DE OUTROS DESCONTADAS - SERÃO ADICIONADAS NA BASE DE CALCULO
	_oSQL:_sQuery += " SELECT"
	_oSQL:_sQuery += " 	'2 - VERBA DE OUTROS NO TITULO' AS TIPO"
	_oSQL:_sQuery += "    ,ZA4_VEND VENDEDOR_VERBA"
	_oSQL:_sQuery += "    ,E3_VEND VENDEDOR_NOTA"
	_oSQL:_sQuery += "    ,ZA5_NUM AS VERBA"
	_oSQL:_sQuery += "    ,E3_NUM AS NOTA"
	_oSQL:_sQuery += "    ,E3_PREFIXO AS SERIE"
	_oSQL:_sQuery += "    ,E3_CODCLI AS CLIENTE"
	_oSQL:_sQuery += "    ,E3_LOJA AS LOJA"
	_oSQL:_sQuery += "    ,E3_PORC AS PERCENTUAL"
	_oSQL:_sQuery += "    ,ZA5.ZA5_VLR AS BASE_COMISSAO"
	_oSQL:_sQuery += "    ,(ZA5.ZA5_VLR * E3_PORC / 100) AS COMISSAO"
	_oSQL:_sQuery += "    ,'ACRESCIMO' AS TP"
	_oSQL:_sQuery += " 	  ,'2' AS TPO"
    _oSQL:_sQuery += "    ,ZA5.ZA5_FILIAL AS FILIAL"
    _oSQL:_sQuery += "    ,ZA5.ZA5_SEQ AS SEQUENCIA"
    _oSQL:_sQuery += "    ,ZA5.ZA5_DTA AS DTA"
    _oSQL:_sQuery += "    ,SE3.E3_DATA AS DTPGTOCOM"
	_oSQL:_sQuery += " FROM " + RetSQLName ("ZA5") + " ZA5 "
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("ZA4") + " ZA4 "
	_oSQL:_sQuery += " 	ON (ZA4.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND ZA4_FILIAL = '" + xFilial('ZA4') + "' " 
	_oSQL:_sQuery += " 			AND ZA4_NUM = ZA5_NUM"
	_oSQL:_sQuery += " 			AND ZA4_VEND != ''"
	_oSQL:_sQuery += " 			AND ZA4_VEND != '" + alltrim(_sVend) +"')"
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("SA3") + " SA3 "
	_oSQL:_sQuery += " 	ON (SA3.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND SA3.A3_COD = ZA4.ZA4_VEND)"
	_oSQL:_sQuery += " LEFT JOIN " + RetSQLName ("SE3") + " SE3 "
	_oSQL:_sQuery += " 	ON (SE3.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND E3_BAIEMI = 'B'"
	_oSQL:_sQuery += " 			AND E3_VEND = '" + alltrim(_sVend) + "'"
	Do case
		Case _nLibPg = 1	
			_oSQL:_sQuery += " 			AND E3_DATA = ''" // comissoes liberadas
		Case _nLibPg = 2
			_oSQL:_sQuery += " 			AND E3_DATA != ''" // comissoes pagas
		Case _nLibPg = 3
			// na rotina automatica não irá verificar a data, gravando a data do E3 ou vazio no ZB0_DTPGTO
	EndCase
	_oSQL:_sQuery += " 			AND E3_NUM = ZA5_DOC"
	_oSQL:_sQuery += " 			AND E3_PREFIXO = ZA5_PREFIX"
	_oSQL:_sQuery += " 			AND E3_PARCELA = ZA5_PARC"
	_oSQL:_sQuery += " 			AND E3_CODCLI = ZA5_CLI"
	_oSQL:_sQuery += " 			AND E3_LOJA = ZA5_LOJA"
	//_oSQL:_sQuery += " 			AND E3_EMISSAO < '"+ dtos(_dtaFin) + "'"
	_oSQL:_sQuery += " 			AND E3_EMISSAO <= '"+ dtos(_dtaFin) + "'"
	_oSQL:_sQuery += " 		)"
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("SE1") + " SE1 "
	_oSQL:_sQuery += " 	ON (SE1.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND SE1.E1_FILIAL = E3_FILIAL"
	_oSQL:_sQuery += " 			AND SE1.E1_NUM = E3_NUM"
	_oSQL:_sQuery += " 			AND SE1.E1_PREFIXO = E3_PREFIXO"
	_oSQL:_sQuery += " 			AND SE1.E1_PARCELA = E3_PARCELA)"
	_oSQL:_sQuery += " WHERE ZA5.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " AND ZA5_FILIAL = '" + xFilial('ZA5') + "' " 
	_oSQL:_sQuery += " AND ZA5_DTA BETWEEN '" + dtos(_dtaIni) + "' AND '" + dtos(_dtaFin) + "'"
	
	_oSQL:_sQuery += " UNION ALL"
	
	//-- DESCONTA VALOR
	_oSQL:_sQuery += " SELECT"
	_oSQL:_sQuery += " 	'3 - BONIFICAÇÕES' AS TIPO"
	_oSQL:_sQuery += "    ,'-' AS VENDEDOR_VERBA"
	_oSQL:_sQuery += "    ,SF2.F2_VEND1 AS VENDEDOR_NOTA"
	_oSQL:_sQuery += "    ,'-' AS VERBA"
	_oSQL:_sQuery += "    ,SF2.F2_DOC AS NOTA"
	_oSQL:_sQuery += "    ,SF2.F2_SERIE AS SERIE"
	_oSQL:_sQuery += "    ,SF2.F2_CLIENTE AS CLIENTE"
	_oSQL:_sQuery += "    ,SF2.F2_LOJA AS LOJA"
	_oSQL:_sQuery += "    ,(SELECT"
	_oSQL:_sQuery += " 			SUM(E1_COMIS1) / COUNT(*)"
	_oSQL:_sQuery += " 		FROM " + RetSQLName ("SE1") + " SE1 "
	_oSQL:_sQuery += " 		WHERE SE1.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 		AND SE1.E1_CLIENTE = SF2.F2_CLIENTE"
	_oSQL:_sQuery += " 		AND SE1.E1_LOJA = SF2.F2_LOJA"
	_oSQL:_sQuery += " 		AND SE1.E1_COMIS1 <> 0"
	_oSQL:_sQuery += " 		AND SE1.E1_VEND1 = '"+alltrim(_sVend)+"'"
	_oSQL:_sQuery += " 		AND SE1.E1_EMISSAO BETWEEN '" + dtos(_dtaAnt) + "' AND '" + dtos(_dtaFin) + "'"
	_oSQL:_sQuery += " 	)"
	_oSQL:_sQuery += " 	AS PERCENTUAL"
	_oSQL:_sQuery += "    ,SUM(SD2.D2_PRCVEN * D2_QUANT) AS BASE_COMISSAO"
	_oSQL:_sQuery += "    ,(SUM(SD2.D2_PRCVEN * D2_QUANT) * (SELECT"
	_oSQL:_sQuery += " 			SUM(E1_COMIS1) / COUNT(*)"
	_oSQL:_sQuery += " 		FROM " + RetSQLName ("SE1") + " SE1 "
	_oSQL:_sQuery += " 		WHERE SE1.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 		AND SE1.E1_CLIENTE IN (SELECT"
	_oSQL:_sQuery += " 				SA1.A1_COD"
	_oSQL:_sQuery += " 			FROM " + RetSQLName ("SA1") + " SA1 "
	_oSQL:_sQuery += " 			WHERE SA1. D_E_L_E_T_ = '' AND SA1.A1_VACBASE = (SELECT "
	_oSQL:_sQuery += " 					SA11.A1_VACBASE "
	_oSQL:_sQuery += " 				FROM " + RetSQLName ("SA1") + " SA11 "
	_oSQL:_sQuery += " 				WHERE SA11. D_E_L_E_T_ = '' AND SA11.A1_COD = SF2.F2_CLIENTE "
	_oSQL:_sQuery += " 				AND SA11.A1_LOJA = SF2.F2_LOJA))"
	_oSQL:_sQuery += " 		AND SE1.E1_LOJA = SF2.F2_LOJA"
	_oSQL:_sQuery += " 		AND SE1.E1_COMIS1 <> 0"
	_oSQL:_sQuery += " 		AND SE1.E1_VEND1 = '"+alltrim(_sVend)+"'"
	_oSQL:_sQuery += " 		AND SE1.E1_EMISSAO BETWEEN '" + dtos(_dtaAnt) + "' AND '" + dtos(_dtaFin) + "'"
	_oSQL:_sQuery += " 	)"
	_oSQL:_sQuery += " 	/ 100) * -1 AS COMISSAO"
	_oSQL:_sQuery += "    ,'DESCONTO' AS TP"
	_oSQL:_sQuery += "    ,'3' AS TPO"
    _oSQL:_sQuery += "    ,SF2.F2_FILIAL AS FILIAL"
    _oSQL:_sQuery += "    ,1 AS SEQUENCIA"
    _oSQL:_sQuery += "    ,SF2.F2_EMISSAO AS DTA"
    _oSQL:_sQuery += "    ,'' AS DTPGTOCOM"
	_oSQL:_sQuery += " FROM " + RetSQLName ("SD2") + " SD2 "
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("SF2") + " SF2 "
	_oSQL:_sQuery += " 	ON (SF2.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND SF2.F2_DOC = SD2.D2_DOC"
	_oSQL:_sQuery += " 			AND SF2.F2_SERIE = SD2.D2_SERIE"
	_oSQL:_sQuery += " 			AND SF2.F2_FILIAL = SD2.D2_FILIAL)"
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("SF4") + " SF4 "
	_oSQL:_sQuery += " 	ON (SF4.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND SF4.F4_CODIGO = SD2.D2_TES"
	_oSQL:_sQuery += " 			AND F4_MARGEM = '3')"
	_oSQL:_sQuery += " WHERE SD2.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " AND SD2.D2_EMISSAO BETWEEN '" + dtos(_dtaIni) + "' AND '" + dtos(_dtaFin) + "'"
	_oSQL:_sQuery += " AND SF2.F2_VEND1 = '"+alltrim(_sVend)+"'"
	_oSQL:_sQuery += " GROUP BY SF2.F2_DOC"
	_oSQL:_sQuery += " 		,SF2.F2_SERIE"
	_oSQL:_sQuery += " 		,SF2.F2_VEND1"
	_oSQL:_sQuery += " 		,SF2.F2_CLIENTE"
	_oSQL:_sQuery += " 		,SF2.F2_LOJA"
	_oSQL:_sQuery += " 		,SF2.F2_FILIAL "
	_oSQL:_sQuery += " 		,SF2.F2_EMISSAO "
	_oSQL:_sQuery += " UNION ALL"
	
	//-- DESCONTA VALOR
	_oSQL:_sQuery += " SELECT"
	_oSQL:_sQuery += " 	'4 - VERBAS BOLETO/DEP' AS TIPO"
	_oSQL:_sQuery += "    ,ZA4_VEND AS VENDEDOR_VERBA"
	_oSQL:_sQuery += "    ,ZA4_VEND AS VENDEDOR_NOTA"
	_oSQL:_sQuery += "    ,ZA5.ZA5_NUM AS VERBA"
	_oSQL:_sQuery += "    ,ZA5.ZA5_DOC AS NOTA"
	_oSQL:_sQuery += "    ,ZA5.ZA5_PREFIX AS SERIE"
	_oSQL:_sQuery += "    ,ZA5.ZA5_CLI AS CLIENTE"
	_oSQL:_sQuery += "    ,ZA5.ZA5_LOJA AS LOJA"
	_oSQL:_sQuery += "    ,(SELECT"
	_oSQL:_sQuery += " 			SUM(E1_COMIS1) / COUNT(*)"
	_oSQL:_sQuery += " 		FROM " + RetSQLName ("SE1") + " SE1 "
	_oSQL:_sQuery += " 		WHERE SE1.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 		AND SE1.E1_CLIENTE IN (SELECT"
	_oSQL:_sQuery += " 				SA1.A1_COD"
	_oSQL:_sQuery += " 			FROM " + RetSQLName ("SA1") + " SA1 "
	_oSQL:_sQuery += " 			WHERE SA1. D_E_L_E_T_ = '' AND SA1.A1_VACBASE = (SELECT "
	_oSQL:_sQuery += " 					SA11.A1_VACBASE "
	_oSQL:_sQuery += " 				FROM " + RetSQLName ("SA1") + " SA11 "
	_oSQL:_sQuery += " 				WHERE SA11. D_E_L_E_T_ = '' AND SA11.A1_COD = ZA5.ZA5_CLI "
	_oSQL:_sQuery += " 				AND SA11.A1_LOJA = ZA5.ZA5_LOJA))"
	_oSQL:_sQuery += " 		AND SE1.E1_LOJA = ZA5.ZA5_LOJA"
	_oSQL:_sQuery += " 		AND SE1.E1_COMIS1 <> 0"
	_oSQL:_sQuery += " 		AND SE1.E1_VEND1 = '"+alltrim(_sVend)+"'"
	_oSQL:_sQuery += " 		AND SE1.E1_EMISSAO BETWEEN '" + dtos(_dtaAnt) + "' AND '" + dtos(_dtaFin) + "')"
	_oSQL:_sQuery += " 	AS PERCENTUAL"
	_oSQL:_sQuery += "    ,ZA5_VLR AS BASE_COMISSAO"
	_oSQL:_sQuery += "    ,(ZA5_VLR * (SELECT"
	_oSQL:_sQuery += " 			SUM(E1_COMIS1) / COUNT(*)"
	_oSQL:_sQuery += " 		FROM " + RetSQLName ("SE1") + " SE1 "
	_oSQL:_sQuery += " 		WHERE SE1.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 		AND SE1.E1_CLIENTE IN (SELECT"
	_oSQL:_sQuery += " 				SA1.A1_COD"
	_oSQL:_sQuery += " 			FROM " + RetSQLName ("SA1") + " SA1 "
	_oSQL:_sQuery += " 			WHERE SA1. D_E_L_E_T_ = '' AND SA1.A1_VACBASE = (SELECT "
	_oSQL:_sQuery += " 					SA11.A1_VACBASE "
	_oSQL:_sQuery += " 				FROM " + RetSQLName ("SA1") + " SA11 "
	_oSQL:_sQuery += " 				WHERE SA11. D_E_L_E_T_ = '' AND SA11.A1_COD = ZA5.ZA5_CLI "
	_oSQL:_sQuery += " 				AND SA11.A1_LOJA = ZA5.ZA5_LOJA))"
	_oSQL:_sQuery += " 		AND SE1.E1_LOJA = ZA5.ZA5_LOJA"
	_oSQL:_sQuery += " 		AND SE1.E1_COMIS1 <> 0"
	_oSQL:_sQuery += " 		AND SE1.E1_VEND1 = '"+alltrim(_sVend)+"'"
	_oSQL:_sQuery += " 		AND SE1.E1_EMISSAO BETWEEN '" + dtos(_dtaAnt) + "' AND '" + dtos(_dtaFin) + "')"
	_oSQL:_sQuery += " 	/ 100) * -1 AS COMISSAO"
	_oSQL:_sQuery += "    ,'DESCONTO' AS TP"
	_oSQL:_sQuery += " 	  ,'4' AS TPO"
    _oSQL:_sQuery += "    ,ZA5.ZA5_FILIAL AS FILIAL"
    _oSQL:_sQuery += "    ,ZA5.ZA5_SEQ AS SEQUENCIA"
    _oSQL:_sQuery += "    ,ZA5.ZA5_DTA AS DTA"
    _oSQL:_sQuery += "    ,'' AS DTPGTOCOM"
	_oSQL:_sQuery += " FROM " + RetSQLName ("ZA5") + " ZA5 "
	_oSQL:_sQuery += " 	," + RetSQLName ("ZA4") + " ZA4 "
	_oSQL:_sQuery += " WHERE ZA5.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " AND ZA4_FILIAL = '" + xFilial('ZA4') + "' " 
	_oSQL:_sQuery += " AND ZA4_NUM = ZA5_NUM"
	_oSQL:_sQuery += " AND ZA4_VEND = '"+alltrim(_sVend)+"'"
	_oSQL:_sQuery += " AND ZA5_DTA BETWEEN '" + dtos(_dtaIni) + "' AND '" + dtos(_dtaFin) + "'"
	_oSQL:_sQuery += " AND ZA5_NUM = ZA5_DOC"
	
	_oSQL:_sQuery += " UNION ALL"
	
	//-- DESCONTA VALOR
	_oSQL:_sQuery += " SELECT"
	_oSQL:_sQuery += " 	'5 - VERBA EM TITULO DE OUTROS' AS TIPO"
	_oSQL:_sQuery += "    ,ZA4_VEND AS VENDEDOR_VERBA"
	_oSQL:_sQuery += "    ,E3_VEND AS VENDEDOR_NOTA"
	_oSQL:_sQuery += "    ,ZA5_NUM AS VERBA"
	_oSQL:_sQuery += "    ,E3_NUM AS NOTA"
	_oSQL:_sQuery += "    ,E3_PREFIXO AS SERIE"
	_oSQL:_sQuery += "    ,E3_CODCLI AS CLIENTE"
	_oSQL:_sQuery += "    ,E3_LOJA AS LOJA"
	_oSQL:_sQuery += "    ,E3_PORC AS PERCENTUAL"
	_oSQL:_sQuery += "    ,ZA5.ZA5_VLR AS BASE_COMISSAO"
	_oSQL:_sQuery += "    ,(ZA5.ZA5_VLR * E3_PORC / 100) * -1 AS COMISSAO"
	_oSQL:_sQuery += "    ,'DESCONTO' AS TP"
	_oSQL:_sQuery += " 	  ,'5' AS TPO"
    _oSQL:_sQuery += "    ,ZA5.ZA5_FILIAL AS FILIAL"
    _oSQL:_sQuery += "    ,ZA5.ZA5_SEQ AS SEQUENCIA"
    _oSQL:_sQuery += "    ,ZA5.ZA5_DTA AS DTA"
    _oSQL:_sQuery += "    ,SE3.E3_DATA AS DTPGTOCOM"
	_oSQL:_sQuery += " FROM " + RetSQLName ("ZA5") + " ZA5 "
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("ZA4") + " ZA4 "
	_oSQL:_sQuery += " 	ON (ZA4.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND ZA4_FILIAL = '" + xFilial('ZA4') + "' " 
	_oSQL:_sQuery += " 			AND ZA4_NUM = ZA5_NUM"
	_oSQL:_sQuery += " 			AND ZA4_VEND != ''"
	_oSQL:_sQuery += " 			AND ZA4_VEND = '"+ alltrim(_sVend)+"')"
	_oSQL:_sQuery += " LEFT JOIN " + RetSQLName ("SE3") + " SE3 "
	_oSQL:_sQuery += " 	ON (SE3.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND E3_BAIEMI = 'B'"
	_oSQL:_sQuery += " 			AND E3_VEND != '"+alltrim(_sVend)+"'"
	Do case
		Case _nLibPg = 1	
			_oSQL:_sQuery += " 			AND E3_DATA = ''" // comissoes liberadas
		Case _nLibPg = 2
			_oSQL:_sQuery += " 			AND E3_DATA != ''" // comissoes pagas
		Case _nLibPg = 3
			// na rotina automatica não irá verificar a data, gravando a data do E3 ou vazio no ZB0_DTPGTO
	EndCase
	_oSQL:_sQuery += " 			AND E3_NUM = ZA5_DOC"
	_oSQL:_sQuery += " 			AND E3_PREFIXO = ZA5_PREFIX"
	_oSQL:_sQuery += " 			AND E3_PARCELA = ZA5_PARC"
	_oSQL:_sQuery += " 			AND E3_CODCLI = ZA5_CLI"
	_oSQL:_sQuery += " 			AND E3_LOJA = ZA5_LOJA"
	_oSQL:_sQuery += " 			AND E3_EMISSAO < '" + dtos(_dtaFin) + "'"
	_oSQL:_sQuery += " 		)"
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("SE1") + " SE1 "
	_oSQL:_sQuery += " 	ON (SE1.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND SE1.E1_FILIAL = E3_FILIAL"
	_oSQL:_sQuery += " 			AND SE1.E1_NUM = E3_NUM"
	_oSQL:_sQuery += " 			AND SE1.E1_PREFIXO = E3_PREFIXO"
	_oSQL:_sQuery += " 			AND SE1.E1_PARCELA = E3_PARCELA)"
	_oSQL:_sQuery += " WHERE ZA5.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " AND ZA5_FILIAL = '" + xFilial('ZA5') + "' " 
	_oSQL:_sQuery += " AND ZA5_DTA BETWEEN '" + dtos(_dtaIni) + "' AND '" + dtos(_dtaFin) + "'"
	
	_oSQL:_sQuery += " UNION ALL"
	
	_oSQL:_sQuery += " SELECT"
	_oSQL:_sQuery += " 	'6 - VERBA EM TITULO SEM COMISSAO' AS TIPO"
	_oSQL:_sQuery += "    ,ZA4_VEND AS VENDEDOR_VERBA"
	_oSQL:_sQuery += "    ,SE1.E1_VEND1 AS VENDEDOR_NOTA"
	_oSQL:_sQuery += "    ,ZA5_NUM AS VERBA"
	_oSQL:_sQuery += "    ,ZA5.ZA5_DOC AS NOTA"
	_oSQL:_sQuery += "    ,ZA5.ZA5_PREFIX AS SERIE"
	_oSQL:_sQuery += "    ,ZA5.ZA5_CLI AS CLIENTE"
	_oSQL:_sQuery += "    ,ZA5.ZA5_LOJA AS LOJA"
	_oSQL:_sQuery += "    ,(SELECT"
	_oSQL:_sQuery += " 			SUM(E1_COMIS1) / COUNT(*)"
	_oSQL:_sQuery += " 		FROM " + RetSQLName ("SE1") + " SE1 "
	_oSQL:_sQuery += " 		WHERE SE1.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 		AND SE1.E1_CLIENTE IN (SELECT"
	_oSQL:_sQuery += " 				SA1.A1_COD "
	_oSQL:_sQuery += " 			FROM " + RetSQLName ("SA1") + " SA1 "
	_oSQL:_sQuery += " 			WHERE SA1. D_E_L_E_T_ = '' AND SA1.A1_VACBASE = (SELECT "
	_oSQL:_sQuery += " 					SA11.A1_VACBASE "
	_oSQL:_sQuery += " 				FROM " + RetSQLName ("SA1") + " SA11 "
	_oSQL:_sQuery += " 				WHERE SA11. D_E_L_E_T_ = '' AND SA11.A1_COD = ZA5.ZA5_CLI "
	_oSQL:_sQuery += " 				AND SA11.A1_LOJA = ZA5.ZA5_LOJA))"
	_oSQL:_sQuery += " 		AND SE1.E1_LOJA = ZA5.ZA5_LOJA"
	_oSQL:_sQuery += " 		AND SE1.E1_COMIS1 <> 0 "
	_oSQL:_sQuery += " 		AND SE1.E1_VEND1 = '" + alltrim(_sVend) + "'"
	_oSQL:_sQuery += " 		AND SE1.E1_EMISSAO BETWEEN '" + dtos(_dtaAnt) + "' AND '" + dtos(_dtaFin) + "')"
	_oSQL:_sQuery += " 	AS PERCENTUAL"
	_oSQL:_sQuery += "    ,ZA5.ZA5_VLR AS BASE_COMISSAO"
	_oSQL:_sQuery += "    ,ZA5.ZA5_VLR * (SELECT"
	_oSQL:_sQuery += " 			SUM(E1_COMIS1) / COUNT(*)"
	_oSQL:_sQuery += " 		FROM " + RetSQLName ("SE1") + " SE1 "
	_oSQL:_sQuery += " 		WHERE SE1.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 		AND SE1.E1_CLIENTE IN (SELECT"
	_oSQL:_sQuery += " 				SA1.A1_COD"
	_oSQL:_sQuery += " 			FROM " + RetSQLName ("SA1") + " SA1 "
	_oSQL:_sQuery += " 			WHERE SA1. D_E_L_E_T_ = '' AND SA1.A1_VACBASE = (SELECT "
	_oSQL:_sQuery += " 					SA11.A1_VACBASE "
	_oSQL:_sQuery += " 				FROM " + RetSQLName ("SA1") + " SA11 "
	_oSQL:_sQuery += " 				WHERE SA11. D_E_L_E_T_ = '' AND SA11.A1_COD = ZA5.ZA5_CLI "
	_oSQL:_sQuery += " 				AND SA11.A1_LOJA = ZA5.ZA5_LOJA))"
	_oSQL:_sQuery += " 		AND SE1.E1_LOJA = ZA5.ZA5_LOJA"
	_oSQL:_sQuery += " 		AND SE1.E1_COMIS1 <> 0 "
	_oSQL:_sQuery += " 		AND SE1.E1_VEND1 = '" + alltrim(_sVend) + "'"
	_oSQL:_sQuery += " 		AND SE1.E1_EMISSAO BETWEEN '" + dtos(_dtaAnt) + "' AND '" + dtos(_dtaFin) + "')"
	_oSQL:_sQuery += " 	/ 100 * -1 AS COMISSAO"
	_oSQL:_sQuery += "    ,'DESCONTO' AS TP"
	_oSQL:_sQuery += " 	  ,'6' AS TPO"
    _oSQL:_sQuery += "    ,ZA5.ZA5_FILIAL AS FILIAL"
    _oSQL:_sQuery += "    ,ZA5.ZA5_SEQ AS SEQUENCIA"
    _oSQL:_sQuery += "    ,ZA5.ZA5_DTA AS DTA"
    _oSQL:_sQuery += "    ,'' AS DTPGTOCOM"
	_oSQL:_sQuery += " FROM " + RetSQLName ("ZA5") + " ZA5 "
	_oSQL:_sQuery += " INNER JOIN ZA4010 ZA4"
	_oSQL:_sQuery += " 	ON (ZA4.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND ZA4_FILIAL = '" + xFilial('ZA4') + "' " 
	_oSQL:_sQuery += " 			AND ZA4_NUM = ZA5_NUM"
	_oSQL:_sQuery += " 			AND ZA4_VEND != ''"
	_oSQL:_sQuery += " 			AND ZA4_VEND = '" + alltrim(_sVend) + "')"
	_oSQL:_sQuery += " INNER JOIN SE1010 SE1"
	_oSQL:_sQuery += " 	ON (SE1.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND SE1.E1_FILIAL = ZA5_FILIAL"
	_oSQL:_sQuery += " 			AND SE1.E1_NUM = ZA5.ZA5_DOC"
	_oSQL:_sQuery += " 			AND SE1.E1_PREFIXO = ZA5.ZA5_PREFIX"
	_oSQL:_sQuery += " 			AND SE1.E1_PARCELA = ZA5.ZA5_PARC"
	_oSQL:_sQuery += " 		)"
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("SA3") + " SA3 "
	_oSQL:_sQuery += " 	ON (SA3.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND SA3.A3_COD = SE1.E1_VEND1"
	_oSQL:_sQuery += " 			AND SA3.A3_COMIS = 0)"
	_oSQL:_sQuery += " INNER JOIN " + RetSQLName ("SA1") + " SA1 "
	_oSQL:_sQuery += " 	ON (SA1.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " 			AND SA1.A1_COD = ZA5.ZA5_CLI)"
	_oSQL:_sQuery += " WHERE ZA5.D_E_L_E_T_ = ''"
	_oSQL:_sQuery += " AND ZA5_FILIAL = '" + xFilial('ZA5') + "' " 
	_oSQL:_sQuery += " AND ZA5_DTA BETWEEN '" + dtos(_dtaIni) + "' AND '" + dtos(_dtaFin) + "'"
	_oSQL:Log ()
	
	_aRet = aclone (_oSQL:Qry2Array ())

Return _aRet